version: '3.8'

services:
  web-sikarate:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    container_name: web-sikarate-app
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    
  # Optional: Development service
  web-sikarate-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3000"
    container_name: web-sikarate-dev
    restart: unless-stopped
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    profiles:
      - dev